package Agenda.gui;

import Agenda.gui.JDialogAlta;
import Agenda.gui.tableModels.ContactosTableModel;
import Agenda.logica.LogicaNegocio;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author miguel
 */
public class JFrameVentana extends javax.swing.JFrame {

    /**
     * Creates new form JFrameVentana
     */
    public JFrameVentana() {
        initComponents();
        jTableAgenda.setModel(new ContactosTableModel(LogicaNegocio.getListaContactos())); //creamos el objeto pasandole al constructor la lista de contactos de la clase logicaNegocio

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAgenda = new javax.swing.JTable();
        jTextFieldError = new javax.swing.JTextField();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuAlta = new javax.swing.JMenu();
        jMenuBaja = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableAgenda);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTextFieldError.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jTextFieldError, java.awt.BorderLayout.PAGE_END);

        jMenuAlta.setText("Alta");
        jMenuAlta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAltaMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenuAlta);

        jMenuBaja.setText("Baja");
        jMenuBaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBajaMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenuBaja);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAltaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAltaMouseClicked
        // TODO add your handling code here:
        jTextFieldError.setText("");
        JDialogAlta ventanaAlta = new JDialogAlta(this, true);
        ventanaAlta.setVisible(true);
        refrescaTabla();
    }//GEN-LAST:event_jMenuAltaMouseClicked

    private void jMenuBajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBajaMouseClicked
        // TODO add your handling code here:
        jTextFieldError.setText("");  //Borro el mensaje de error
        //Comprobamos si hay una fila seleccionada
        int fila;
        fila=jTableAgenda.getSelectedRow();
        if (fila==-1){ //si no hay una fila seleccionada
            jTextFieldError.setText("Selecciona una fila");
        } else {  //si la fila esta seleccionada la borramos de si datatable
            ContactosTableModel ctm = (ContactosTableModel)jTableAgenda.getModel(); //recuperamos su TableModel
            ctm.deleteRow(fila); 
        }
    }//GEN-LAST:event_jMenuBajaMouseClicked
    
    private void refrescaTabla() {
        ContactosTableModel ctm = (ContactosTableModel) jTableAgenda.getModel();  //recupero el TableModel de la tabla
        TableRowSorter<ContactosTableModel> tablaOrdenadora = new TableRowSorter<>(ctm);
        jTableAgenda.setRowSorter(tablaOrdenadora);
        //AQUI METEREIAMOS EL FILTRO PERO NO ME GUSTA USARLO
        //tablaOrdenadora.setRowFilter(RowFilter.regexFilter("^a", 4));
        ctm.refrescar();  //lanzo su metodo para refrescarlo
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAlta;
    private javax.swing.JMenu jMenuBaja;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAgenda;
    private javax.swing.JTextField jTextFieldError;
    // End of variables declaration//GEN-END:variables
}
